import '@/abstract/variables.scss'
import '@/base/globals.scss'
import '@/animations/globalAnimations.scss'
import localFont from "next/font/local"
import Navbar from './components/Navbar'

const public_Sans = localFont({
  src: "./localFonts/PublicSans-Medium.ttf",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${public_Sans.className} body`} id='body'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
